[project]
name = "egemma"
version = "0.3.0"
requires-python = ">=3.13"

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing --cov-fail-under=80 --import-mode=importlib"
testpaths = [
    "tests/",
]
pythonpath = [".", "src"]
